src/Entity/Event.php
<?php

namespace App\Entity;

use App\Model\EventState;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateLimitRegister;

    /**
     * @ORM\Column(type="integer")
     */
    private $MaxRegister;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $eventInfos;

    /**
     * @ORM\ManyToOne(targetEntity=Place::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $place;

    /**
     * @ORM\Column(type="string")
     */
    private $state;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $site;

    /**
     * @ORM\ManyToMany(targetEntity=Member::class, inversedBy="events")
     */
    private $members;

    /**
     * @ORM\ManyToOne(targetEntity=Member::class, inversedBy="organizedEvents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organizer;

    public function __construct()
    {
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDateLimitRegister(): ?\DateTimeInterface
    {
        return $this->dateLimitRegister;
    }

    public function setDateLimitRegister(\DateTimeInterface $dateLimitRegister): self
    {
        $this->dateLimitRegister = $dateLimitRegister;

        return $this;
    }

    public function getMaxRegister(): ?int
    {
        return $this->MaxRegister;
    }

    public function setMaxRegister(int $MaxRegister): self
    {
        $this->MaxRegister = $MaxRegister;

        return $this;
    }

    public function getEventInfos(): ?string
    {
        return $this->eventInfos;
    }

    public function setEventInfos(string $eventInfos): self
    {
        $this->eventInfos = $eventInfos;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getState(): ?EventState
    {
        if ($this->state) {
            return EventState::fromValue($this->state);
        } else {
            return null;
        }
    }

    public function setState(?EventState $state): self
    {
        if ($state) {
            $this->state = $state->getIdentifier();
        }
        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    /**
     * @return Collection<int, Member>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Member $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
        }

        return $this;
    }

    public function removeMember(Member $member): self
    {
        $this->members->removeElement($member);

        return $this;
    }

    public function getOrganizer(): ?Member
    {
        return $this->organizer;
    }

    public function setOrganizer(?Member $organizer): self
    {
        $this->organizer = $organizer;

        return $this;
    }

}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\Place;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la sortie : ',
                'required' => false
            ])
            ->add('startDate', DateTimeType::class, [
                'label' => 'Date et heure de la sortie : ',
                'widget' => 'single_text'
            ])
            ->add('dateLimitRegister', DateType::class, [
                'label' => 'Date limite d\'inscription : ',
                'widget' => 'single_text'
            ])
            ->add('MaxRegister', NumberType::class, [
                'label' => 'Nombre de places : ',
            ])
            ->add('duration', NumberType::class, [
                'label' => 'Durée : ',
            ])
            ->add('eventInfos', TextareaType::class, [
                'label' => 'Description et Infos : ',
            ])
            ->add('place', EntityType::class, [
                'label' => 'Place : ',
                'class' => Place::class,
                'choice_label' => 'name',
            ])

            ->add('save', SubmitType::class, ["label" => "Créer"])
            ->add('saveAndPublish', SubmitType::class, ['label' => 'Publier'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\User;
use App\Form\CancelEventFormType;
use App\Form\EventType;
use App\Model\CancelEventModel;
use App\Model\EventState;
use App\Repository\EventRepository;
use App\Services\EventServices;
use App\Services\MailerServices;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Event controller.
 * Manages events.
 */
class EventController extends AbstractController
{
    private $logger;
    private $eventServices;
    private $mailerServices;
    private $eventRepository;

    public function __construct(LoggerInterface $logger,
                                EventServices $eventServices,
                                MailerServices $mailerServices,
                                EventRepository $eventRepository
                                )
    {
        $this->logger = $logger;
        $this->eventServices = $eventServices;
        $this->mailerServices = $mailerServices;
        $this->eventRepository = $eventRepository;
    }

    /**
     * @Route("/events/{id}", name="app_event_detail", requirements={"id"="\d+"})
     */
    public function detailEvents(Event $availableEvent): Response
    {
        $user = $this->getUser();
        $memberInEvent = $availableEvent->getMembers();

        return $this->render('event/detail.html.twig', [
            "availableEvent" => $availableEvent,
            "user" => $user,
            "memberInEvent" => $memberInEvent
        ]);
    }

    /**
     * @Route("/events/{id}/cancel", name="app_event_cancel_show", requirements={"id" = "\d+"}, methods={"GET"})
     */
    public function showCancelEvent(Event $event, Request $request): Response
    {
        $this->logger->info("Accès à la page d'annulation de l'événement {$event->getId()}");

        if ($event->getId() === null) {
            $this->logger->warning("L'événement fourni est invalide.");
            $this->addFlash("error", "L'événement fourni n'existe pas ou plus.");
            return $this->redirectToRoute("app_main");
        }

        if (!$this->getUser()) {
            $this->logger->warning("Utilisateur non authentifié sur la plateforme.");
            $this->addFlash("error", "Vous devez être authentifié sur la plateforme pour accéder à cette fonctionnalité.");
            return $this->redirectToRoute("app_login");
        }

        if (!($this->getUser() instanceof User)) {
            $this->logger->warning("L'utilisateur n'est pas une instance de App\Entity\User.");
            $this->addFlash("error", "Une erreur interne est survenue, ce service n'est pas disponible pour le moment.");
            return $this->redirectToRoute("app_main");
        }

        $profile = $this->getUser()->getProfil();

        if (!$profile) {
            $this->logger->warning("L'utilisateur courant n'a pas de profil associé.");
            $this->addFlash("error", "Une erreur interne est survenue, ce service n'est pas disponible pour le moment.");
            return $this->redirectToRoute("app_main");
        }

        $admin = $this->getUser()->getRoles()[0];

        if (!($this->eventServices->isUserOrganizerOfEvent($this->getUser(), $event) || $admin)) {
            $this->logger->info("Tentative d'annulation de l'événement {$event->getId()} par l'utilisateur non organisateur {$this->getUser()->getUsername()}");
            $this->addFlash("error", "Vous n'avez pas la permission d'annuler un événement dont vous n'êtes pas l'organisateur.");
            return $this->redirectToRoute("app_main");
        }

        if (EventState::isFinished($event->getState())) {
            $this->logger->info("Annulation d'un événement déjà terminé.");
            $this->addFlash("error", "Vous ne pouvez pas annuler un événement déjà terminé.");
            return $this->redirectToRoute("app_event_detail", ["id" => $event->getId()]);
        }

        $cancelFormData = new CancelEventModel();
        $cancelFormData->setEventId($event->getId());
        $cancelForm = $this->createForm(CancelEventFormType::class, $cancelFormData);

        return $this->render("event/cancel.html.twig", [
            "cancelForm" => $cancelForm->createView(),
            "eventId" => $event->getId()
        ]);
    }

    /**
     * @Route("/events/{id}/cancel", name="app_event_cancel", requirements={"id" = "\d+"}, methods={"POST"})
     */
    public function cancelEvent(Event $event, Request $request): Response
    {
        $this->logger->info("Appel du service d'annulation d'événement.");

        // Check if the user is authentified
        $currentUser = $this->getUser();
        if (!$currentUser) {
            $this->logger->warning("Utilisateur non authentifié sur la plateforme.");
            $this->addFlash("error", "Vous devez être authentifié sur l'application pour faire ceci.");
            return $this->redirectToRoute("app_login");
        }

        // CSRF security check
        $csrfToken = $request->request->get("token");
        if (!$this->isCsrfTokenValid('cancel-event-' . $event->getId(), $csrfToken)) {
            $this->logger->warning("Tentative de suppression frauduleuse d'événement. Tokens CSRF invalides.");
            $this->addFlash("error", "Validation de la demande impossible.");
            return $this->redirectToRoute("app_main");
        }

        // Check if the event is archived
        if ($this->eventServices->isEventArchived($event)) {
            $this->logger->info("Tentative de suppression d'un évènement archivé.");
            $this->addFlash("error", "Impossible d'annuler une sortie déjà terminée et archivée.");
            return $this->redirectToRoute("app_event_detail", ["id" => $event->getId()]);
        }

        $admin = $this->getUser()->getRoles()[0];

        // Check if the used is allowed to cancel the event
        if (!($this->eventServices->isUserOrganizerOfEvent($currentUser, $event) || $admin)) {
            $this->logger->info("Tentative de suppression d'un événement dont l'utilisateur n'est pas organisateur.");
            $this->addFlash("error", "Vous ne pouvez pas annuler cet événement, vous n'en êtes pas l'organisateur.");
            return $this->redirectToRoute("app_event_detail", ["id" => $event->getId()]);
        }

        // Cancel the event and send emails if needed
        $removed = $this->eventServices->cancelEvent($event);
        if ($removed) {
            $this->logger->info("L'événement \"{$event->getName()}\" a été supprimé.");
            $this->addFlash("success", "L'événement a bien été annulé.");
            $this->mailerServices->sendCancellationMail($event, "L'événement \"{$event->getName()}\" a été annulé.");
            return $this->redirectToRoute("app_main");
        } else {
            $this->addFlash("error", "Impossible d'annuler l'événement, une erreur interne est survenue.");
            return $this->redirectToRoute("app_event_detail", ["id" => $event->getId()]);
        }
    }

    /**
     * @Route("/events/{id}/subscribe", name="app_event_inscription", requirements={"id"="\d+"})
     */
    public function addMemberToEvent(Request $request, Event $availableEvent): Response {
        $user = $this->getUser();

        if (!$user) {
            $this->logger->warning("L'utilisateur n'est pas authentifié sur la plateforme.");
            $this->addFlash("error", "Vous devez vous authentifier pour accéder à cette fonctionnalité.");
            return $this->redirectToRoute("app_login");
        }

        if (!($user instanceof User)) {
            $this->logger->debug("Une erreur interne est survenue: l'utilisateur n'est pas une instance de User.");
            $this->addFlash("error", "Une erreur interne est survenue.");
            return $this->redirectToRoute("app_main");
        }

        $member = $user->getProfil();

        if(!$member) {
            $this->logger->warning("Utilisateur non authentifié sur la plateforme.");
            $this->addFlash("error", "Vous devez être authentifié sur l'application pour faire ceci.");
            return $this->redirectToRoute("app_login");
        }

        //verifier si l'evenement n'est pas nul
        if(!$availableEvent){
            $this->logger->warning("L'évènement est nul.");
            $this->addFlash("error", "Il n'y pas d'évènement en cours");
            return $this->redirectToRoute("app_main");
        }

        //verifier si l'evenement n'est pas cloturé
        if($this->eventServices->isEventSubscribtionClosed($availableEvent)) {
            $this->logger->info("L'inscription n'est plus possible, l'évènement est cloturé.");
            $this->addFlash("error", "L'inscription n'est plus possible, l'évènement est cloturé.");
            return $this->redirectToRoute("app_main");
        }

        //verifier si il ne participe pas deja a levenement
        if ($this->eventServices->isUserRegisteredOnEvent($availableEvent, $member)) {
            $this->logger->info("L'utilisateur {$member->getId()} est déjà inscrit à l'événement {$availableEvent->getId()}");
            $this->addFlash("error", "Vous êtes déjà inscrit à cet évènement.");
            return $this->redirectToRoute("app_event_detail", ["id" => $availableEvent->getId()]);
        }

        $this->eventRepository->addMemberToEvent($availableEvent, $member, true);
        // $this->memberRepository->addEventToMember($member, $availableEvent, false);
        $this->addFlash("success", "Vous vous êtes bien enregistré à l'évènement");

        return $this->redirectToRoute('app_event_detail', ['id' => $availableEvent->getId()]);
    }

    /**
     * Unsubs the current user from the given event

templates/event/cancel.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{{ form_start(cancelForm) }}
        <h2>Annuler un événement</h2>
        
        <input type="hidden" name="token" value="{{ csrf_token('cancel-event-' ~ eventId) }}">
        {{ form_row(cancelForm.eventId) }}

        {{ form_label(cancelForm.cancelMessage) }}
        {{ form_widget(cancelForm.cancelMessage) }}
    {{ form_end(cancelForm) }}

{% endblock %}

templates/event/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Évènements disponibles{% endblock %}

{% block body %}
<main class="content-container" id="maincontent">
    <h1>Evénement - {{availableEvent.name}}</h1>
    {% include 'partials/_flash.html.twig' %}

    <div> 
        <div>
            <p>Nom de la sortie</p>
            <input type="text" value="{{ availableEvent.name }}" readonly>
        </div>
        <div>
            <p>Ville organisatrice</p>
            <input type="text" value="{{ availableEvent.site.name }}" readonly>
        </div>
        <div>
            <p>Date de la sortie</p>
            <input type="text" value="{{ availableEvent.startDate | date('m/d/Y') }}" readonly>
        </div>
        <div>
            <p>Lieu</p>
            <input type="text" value="{{ availableEvent.place.name }}" readonly>
        </div>
        <div>
            <p>Date limite d'inscription</p>
            <input type="text" value="{{ availableEvent.dateLimitRegister|date('m/d/Y') }}" readonly>
        </div>
        <div>
            <p>Rue</p>
            <input type="text" value="{{ availableEvent.place.street }}" readonly>
        </div>
        <div>
            <p>Nombre de places</p>
            <input type="text" value="{{ availableEvent.maxRegister }}" readonly>
        </div>
        <div>
            <p>Code postal</p>
            <input type="text" value="{{ availableEvent.place.city.postCode }}" readonly>
        </div>
        <div>
            <p>Durée (minutes)</p>
            <input type="text" value="{{ availableEvent.duration }}" readonly>
        </div>
        <div>
            <p>Latitude</p>
            <input type="text" value="{{ availableEvent.place.latitude }}" readonly>
        </div>
        <div>
            <p>Description et infos</p>
            <input type="text" value="{{ availableEvent.eventInfos }}" readonly>
        </div>
        <div>
            <p>Longitude</p>
            <input type="text" value="{{ availableEvent.place.longitude }}" readonly>
        </div>
    </div>
    
    <section>
        <h3> Liste des participants Inscrits </h3>
        
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th scope="col">Pseudo</th>
                        <th scope="col">Nom</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in memberInEvent %}
                    <tr>
                        <td>{{ member.user.username|capitalize }}</td>
                        <td>{{ member.firstName|capitalize }} {{ member.name|upper }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</main>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
{% include "partials/_flash.html.twig" %}
<main class="content-container stack" id="maincontent">
    <h1>Créer une sortie</h1>

    {{ form_start(form) }}
    <div class="stack">
        <div class="field_type">
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
        </div>
        <div class="field_type">
            {{ form_label(form.startDate) }}
            {{ form_widget(form.startDate) }}
        </div>
        <div class="field_type">
            {{ form_label(form.dateLimitRegister) }}
            {{ form_widget(form.dateLimitRegister) }}
        </div>
        <div class="field_type">
            {{ form_label(form.MaxRegister) }}
            {{ form_widget(form.MaxRegister) }}
        </div>
        <div class="field_type">
            {{ form_label(form.duration) }}
            {{ form_widget(form.duration) }}
        </div>
        <div class="field_type">
            {{ form_label(form.eventInfos) }}
            {{ form_widget(form.eventInfos) }}
        </div>
        <div class="field_type">
            {{ form_label(form.place) }}
            {{ form_widget(form.place) }}
        </div>
        <div>
            {{ form_widget(form.save) }}
            {{ form_widget(form.saveAndPublish) }}
        </div>
    </div>
    {{ form_end(form) }}

    <a class="btn" href="{{ path('app_main') }}">back to home</a>
</main>
{% endblock %}

templates/event/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Évènements disponibles{% endblock %}

{% block body %}
<main class="content-container" id="maincontent">
    <h1>Évènements disponibles</h1>
    {% include 'partials/_flash.html.twig' %}
    {{ form_start(form) }}
        <div class="stack"> 
            <div class="field_type">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
            </div>
            <div class="field_type">
                <p>Ville organisatrice</p>
                <input type="text" value="{{ availableEvent.site.name }}">
            </div>
            <div class="field_type">
                {{ form_label(form.startDate) }}
                {{ form_widget(form.startDate) }}
            </div>
            <div class="field_type">
                {{ form_label(form.place) }}
                {{ form_widget(form.place) }}
            </div>
            <div class="field_type">
                {{ form_label(form.dateLimitRegister) }}
                {{ form_widget(form.dateLimitRegister) }}
            </div>
            <div class="field_type">
                <p>Date limite d'inscription</p>
                <input type="text" value="{{ availableEvent.dateLimitRegister|date('m/d/Y') }}" readonly>
            </div>
            <div class="field_type">
                <p>Rue</p>
                <input type="text" value="{{ availableEvent.place.street }}">
            </div>
            <div class="field_type">
                {{ form_label(form.MaxRegister) }}
                {{ form_widget(form.MaxRegister) }}
            </div>
            <div class="field_type">
                <p>Code postal</p>
                <input type="text" value="{{ availableEvent.place.city.postCode }}">
            </div>
            <div class="field_type">
                {{ form_label(form.duration) }}
                {{ form_widget(form.duration) }}
            </div>
            <div class="field_type">
                <p>Latitude</p>
                <input type="text" value="{{ availableEvent.place.latitude }}">
            </div>
            <div class="field_type">
                {{ form_label(form.eventInfos) }}
                {{ form_widget(form.eventInfos) }}
            </div>
            <div class="field_type">
                <p>Longitude</p>
                <input type="text" value="{{ availableEvent.place.longitude }}">
            </div>
            <div>
                {{ form_widget(form.save) }} 
            </div>
        </div>
        {{ form_end(form) }}
</main>
{% endblock %}